spring:
  application:
    name: Config-dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    servis-url:
      defaultZone: http://localhost:8761/eureka
    
